image: mediacurrent/mc-bb-pipelines:latest

pipelines:
  pull-requests:
    dev:
      - step:
          script:
          - git branch
          - git config user.email "briwagner@outlook.com"
          - git config user.name "Brian Wagner"
          - git remote -v
          - git remote add github git@github.com:briwagner/bbucket-pipeline-clone.git
          - git remote -v
          - git checkout master
          - git push github master
  branches:
    dev:
      - step:
          script:
          - npm run build
          - git add ./appdist
          - git commit -m "add build files"
    master:
      - step:
          - git branch
          - git config user.email "briwagner@outlook.com"
          - git config user.name "Brian Wagner"
          - git remote -v
          - git remote add github git@github.com:briwagner/bbucket-pipeline-clone.git
          - git remote -v
          - git checkout master
          - git push github master
