image: mediacurrent/mc-bb-pipelines:latest

pipelines:
  pull-requests:
    dev:
      - step:
          caches:
            - node
          script:
          - git branch
          - npm install
          - npm run test
  branches:
      dev:
        - step:
            caches:
              - node
            script:
            - npm install
            - npm run build
            - git add ./appdist
            - git commit -m "add build files [skip ci]"
            - git push origin dev
      master:
        - step:
            caches:
              - node
            script:
              - git branch
              - git config user.email "briwagner@outlook.com"
              - git config user.name "Brian Wagner"
              - git remote -v
              - git remote add github git@github.com:briwagner/bbucket-clone-test.git
              - git remote -v
              - git checkout master
              - git push github master
